# Generated by Django 4.2.30 on 2026-06-17 04:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_alter_author_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='series',
        ),
        migrations.CreateModel(
            name='BookSeriesMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.PositiveIntegerField()),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='series_memberships', to='books.book')),
                ('series', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_memberships', to='books.bookseries')),
            ],
            options={
                'ordering': ['series', 'index'],
                'unique_together': {('book', 'series')},
            },
        ),
        migrations.AddField(
            model_name='book',
            name='series',
            field=models.ManyToManyField(blank=True, related_name='books', through='books.BookSeriesMembership', to='books.bookseries'),
        ),
    ]
