# Generated by Django 4.2.30 on 2026-06-17 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_remove_book_series_bookseriesmembership_book_series'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookseries',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
