# Generated by Django 4.2.30 on 2026-06-17 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0007_alter_book_description'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BookFile',
            new_name='File',
        ),
        migrations.RenameModel(
            old_name='BookSeries',
            new_name='Series',
        ),
        migrations.RenameModel(
            old_name='BookSeriesMembership',
            new_name='SeriesMembership',
        ),
    ]
