# Generated by Django 4.2.30 on 2026-06-17 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0008_rename_bookfile_file_rename_bookseries_series_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='genre',
            name='description',
        ),
    ]
