# Generated by Django 4.2.30 on 2026-06-20 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0010_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='books/covers'),
        ),
    ]
