# Generated by Django 4.2.30 on 2026-06-20 09:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("events", "0001_initial"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="event",
            name="events_even_target__b09fcd_idx",
        ),
        migrations.RemoveIndex(
            model_name="event",
            name="anonymous_id",
        ),
        migrations.RemoveField(
            model_name="event",
            name="target_id",
        ),
        migrations.RemoveField(
            model_name="event",
            name="target_type",
        ),
        migrations.AddField(
            model_name="event",
            name="content_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="contenttypes.contenttype",
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="object_id",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name="event",
            index=models.Index(
                fields=["content_type", "object_id"],
                name="events_even_content_23e6b7_idx",
            ),
        ),
    ]
