# Generated by Django 4.2.30 on 2026-06-20 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_remove_event_events_even_target__b09fcd_idx_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='anonymous_id',
        ),
    ]
