# Generated by Django 4.2.30 on 2026-06-21 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0002_remove_event_events_even_target__b09fcd_idx_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="event_type",
            field=models.CharField(
                choices=[
                    ("signup", "Sign Up"),
                    ("login", "Login"),
                    ("logout", "Logout"),
                    ("book:download", "Book download"),
                    ("book:view", "Book viewed"),
                    ("book:rated", "Book rated"),
                ],
                max_length=50,
            ),
        ),
    ]
