# Generated by Django 4.2.30 on 2026-06-23 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_alter_event_event_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_type',
            field=models.CharField(choices=[('signup', 'Sign Up'), ('login', 'Login'), ('logout', 'Logout'), ('book:download', 'Book download'), ('book:view', 'Book viewed'), ('list:book:view', 'Book list viewed'), ('book:rated', 'Book rated'), ('book:search', 'Books searched')], max_length=50),
        ),
    ]
