# Generated by Django 4.2.11 on 2026-05-02 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='list',
            name='is_public',
            field=models.BooleanField(default=False),
        ),
    ]
