# Generated by Django 4.2.30 on 2026-06-23 13:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('books', '0012_alter_rating_unique_together'),
        ('lists', '0002_list_is_public'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='list',
            name='is_public',
        ),
        migrations.AddField(
            model_name='list',
            name='books',
            field=models.ManyToManyField(blank=True, related_name='lists', to='books.book'),
        ),
        migrations.AddField(
            model_name='list',
            name='description',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='list',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='lists/'),
        ),
        migrations.AddField(
            model_name='list',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='list',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
