# Generated by Django 4.2.30 on 2026-06-24 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0003_remove_list_is_public_list_books_list_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='list',
            name='image',
        ),
        migrations.AddField(
            model_name='list',
            name='cover',
            field=models.CharField(blank=True, null=True),
        ),
    ]
