# Generated by Django 4.2.30 on 2026-06-25 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0004_remove_list_image_list_cover'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='cover',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
