export const books = [
  { slug: "la-paciente-silenciosa", title: "La paciente silenciosa", author: "Alex Michaelides", genre: "Misterio", type: "Novela", format: "EPUB · PDF", year: "2019", rating: 4, description: "Una pintora deja de hablar tras un crimen inexplicable. Un thriller psicológico sobre la obsesión, el silencio y la verdad.", cover: "left" },
  { slug: "circe", title: "Circe", author: "Madeline Miller", genre: "Fantasía", type: "Novela", format: "EPUB", year: "2018", rating: 5, description: "La hechicera más fascinante de la mitología cuenta su propia historia en una novela luminosa sobre poder, exilio y libertad.", cover: "center" },
  { slug: "yellowface", title: "Yellowface", author: "R. F. Kuang", genre: "Ficción", type: "Libro", format: "EPUB · PDF", year: "2023", rating: 4, description: "Una sátira afilada sobre la ambición literaria, la identidad y las historias que creemos tener derecho a contar.", cover: "right" },
  { slug: "el-infinito-en-un-junco", title: "El infinito en un junco", author: "Irene Vallejo", genre: "Ensayo", type: "Libro", format: "EPUB · PDF", year: "2019", rating: 5, description: "Un viaje apasionante por la invención de los libros y las personas que los han protegido a través del tiempo.", cover: "left" },
  { slug: "proyecto-hail-mary", title: "Proyecto Hail Mary", author: "Andy Weir", genre: "Ficción", type: "Novela", format: "EPUB", year: "2021", rating: 5, description: "Un astronauta despierta solo y debe resolver un misterio científico para salvar a la humanidad.", cover: "center" },
  { slug: "persépolis", title: "Persépolis", author: "Marjane Satrapi", genre: "Ficción", type: "Cómic", format: "PDF", year: "2000", rating: 5, description: "Una memoria gráfica íntima, lúcida y llena de humor sobre crecer entre dos mundos.", cover: "right" },
];

export type Book = (typeof books)[number];